/*
 * This file is generated by jOOQ.
 */
package com.datadome.botdetector.analysis.infra.jooq.codegen.tables.records;


import com.datadome.botdetector.analysis.infra.jooq.codegen.tables.JooqLogFileCursor;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogFileCursorRecord extends TableRecordImpl<LogFileCursorRecord> implements Record2<Long, OffsetDateTime> {

    private static final long serialVersionUID = 1454720246;

    /**
     * Setter for <code>PUBLIC.LOG_FILE_CURSOR.CURSOR</code>.
     */
    public void setCursor(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.LOG_FILE_CURSOR.CURSOR</code>.
     */
    public Long getCursor() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.LOG_FILE_CURSOR.DATE</code>.
     */
    public void setDate(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.LOG_FILE_CURSOR.DATE</code>.
     */
    public OffsetDateTime getDate() {
        return (OffsetDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, OffsetDateTime> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, OffsetDateTime> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return JooqLogFileCursor.T_LOG_FILE_CURSOR.CURSOR;
    }

    @Override
    public Field<OffsetDateTime> field2() {
        return JooqLogFileCursor.T_LOG_FILE_CURSOR.DATE;
    }

    @Override
    public Long component1() {
        return getCursor();
    }

    @Override
    public OffsetDateTime component2() {
        return getDate();
    }

    @Override
    public Long value1() {
        return getCursor();
    }

    @Override
    public OffsetDateTime value2() {
        return getDate();
    }

    @Override
    public LogFileCursorRecord value1(Long value) {
        setCursor(value);
        return this;
    }

    @Override
    public LogFileCursorRecord value2(OffsetDateTime value) {
        setDate(value);
        return this;
    }

    @Override
    public LogFileCursorRecord values(Long value1, OffsetDateTime value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LogFileCursorRecord
     */
    public LogFileCursorRecord() {
        super(JooqLogFileCursor.T_LOG_FILE_CURSOR);
    }

    /**
     * Create a detached, initialised LogFileCursorRecord
     */
    public LogFileCursorRecord(Long cursor, OffsetDateTime date) {
        super(JooqLogFileCursor.T_LOG_FILE_CURSOR);

        set(0, cursor);
        set(1, date);
    }
}
