/*
 * This file is generated by jOOQ.
 */
package com.datadome.botdetector.analysis.infra.jooq.codegen.tables.records;


import com.datadome.botdetector.analysis.infra.jooq.codegen.tables.JooqLogLine;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogLineRecord extends TableRecordImpl<LogLineRecord> implements Record4<String, String, OffsetDateTime, String> {

    private static final long serialVersionUID = 2109208295;

    /**
     * Setter for <code>PUBLIC.LOG_LINE.IP</code>.
     */
    public void setIp(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.LOG_LINE.IP</code>.
     */
    public String getIp() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.LOG_LINE.USER_AGENT</code>.
     */
    public void setUserAgent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.LOG_LINE.USER_AGENT</code>.
     */
    public String getUserAgent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.LOG_LINE.DATE</code>.
     */
    public void setDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.LOG_LINE.DATE</code>.
     */
    public OffsetDateTime getDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>PUBLIC.LOG_LINE.REFERER</code>.
     */
    public void setReferer(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.LOG_LINE.REFERER</code>.
     */
    public String getReferer() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, OffsetDateTime, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, OffsetDateTime, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JooqLogLine.T_LOG_LINE.IP;
    }

    @Override
    public Field<String> field2() {
        return JooqLogLine.T_LOG_LINE.USER_AGENT;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return JooqLogLine.T_LOG_LINE.DATE;
    }

    @Override
    public Field<String> field4() {
        return JooqLogLine.T_LOG_LINE.REFERER;
    }

    @Override
    public String component1() {
        return getIp();
    }

    @Override
    public String component2() {
        return getUserAgent();
    }

    @Override
    public OffsetDateTime component3() {
        return getDate();
    }

    @Override
    public String component4() {
        return getReferer();
    }

    @Override
    public String value1() {
        return getIp();
    }

    @Override
    public String value2() {
        return getUserAgent();
    }

    @Override
    public OffsetDateTime value3() {
        return getDate();
    }

    @Override
    public String value4() {
        return getReferer();
    }

    @Override
    public LogLineRecord value1(String value) {
        setIp(value);
        return this;
    }

    @Override
    public LogLineRecord value2(String value) {
        setUserAgent(value);
        return this;
    }

    @Override
    public LogLineRecord value3(OffsetDateTime value) {
        setDate(value);
        return this;
    }

    @Override
    public LogLineRecord value4(String value) {
        setReferer(value);
        return this;
    }

    @Override
    public LogLineRecord values(String value1, String value2, OffsetDateTime value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LogLineRecord
     */
    public LogLineRecord() {
        super(JooqLogLine.T_LOG_LINE);
    }

    /**
     * Create a detached, initialised LogLineRecord
     */
    public LogLineRecord(String ip, String userAgent, OffsetDateTime date, String referer) {
        super(JooqLogLine.T_LOG_LINE);

        set(0, ip);
        set(1, userAgent);
        set(2, date);
        set(3, referer);
    }
}
