version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  app:
    container_name: bot-detector-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:h2:~/bdetector
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_RABBITMQ_HOST=rabbitmq
      - RABBIT_HOST=rabbitmq
      - SPRING_H2_CONSOLE_SETTINGS.WEB-ALLOW-OTHERS=true
    depends_on:
      - rabbitmq
    network_mode: "host"
