/*
 * This file is generated by jOOQ.
 */
package com.datadome.botdetector.analysis.infra.jooq.codegen;


import com.datadome.botdetector.analysis.infra.jooq.codegen.tables.JooqLogLine;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_LOG_LINE__IP = Indexes0.IDX_LOG_LINE__IP;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index IDX_LOG_LINE__IP = Internal.createIndex("IDX_LOG_LINE__IP", JooqLogLine.T_LOG_LINE, new OrderField[] { JooqLogLine.T_LOG_LINE.IP }, false);
    }
}
