/*
 * This file is generated by jOOQ.
 */
package com.datadome.botdetector.analysis.infra.jooq.codegen;


import com.datadome.botdetector.analysis.infra.jooq.codegen.tables.JooqLogFileCursor;
import com.datadome.botdetector.analysis.infra.jooq.codegen.tables.JooqLogLine;
import com.datadome.botdetector.analysis.infra.jooq.codegen.tables.JooqLogLineHit;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1789064685;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.LOG_FILE_CURSOR</code>.
     */
    public final JooqLogFileCursor T_LOG_FILE_CURSOR = JooqLogFileCursor.T_LOG_FILE_CURSOR;

    /**
     * The table <code>PUBLIC.LOG_LINE</code>.
     */
    public final JooqLogLine T_LOG_LINE = JooqLogLine.T_LOG_LINE;

    /**
     * The table <code>PUBLIC.LOG_LINE_HIT</code>.
     */
    public final JooqLogLineHit T_LOG_LINE_HIT = JooqLogLineHit.T_LOG_LINE_HIT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            JooqLogFileCursor.T_LOG_FILE_CURSOR,
            JooqLogLine.T_LOG_LINE,
            JooqLogLineHit.T_LOG_LINE_HIT);
    }
}
