/*
 * This file is generated by jOOQ.
 */
package com.datadome.botdetector.analysis.infra.jooq.codegen;


import com.datadome.botdetector.analysis.infra.jooq.codegen.tables.JooqLogFileCursor;
import com.datadome.botdetector.analysis.infra.jooq.codegen.tables.JooqLogLine;
import com.datadome.botdetector.analysis.infra.jooq.codegen.tables.JooqLogLineHit;


/**
 * Convenience access to all tables in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.LOG_FILE_CURSOR</code>.
     */
    public static final JooqLogFileCursor T_LOG_FILE_CURSOR = JooqLogFileCursor.T_LOG_FILE_CURSOR;

    /**
     * The table <code>PUBLIC.LOG_LINE</code>.
     */
    public static final JooqLogLine T_LOG_LINE = JooqLogLine.T_LOG_LINE;

    /**
     * The table <code>PUBLIC.LOG_LINE_HIT</code>.
     */
    public static final JooqLogLineHit T_LOG_LINE_HIT = JooqLogLineHit.T_LOG_LINE_HIT;
}
